---
- name: Configure awx

  hosts: awx_app

  become: yes

  vars:

    awx_cli_conf: ~/.tower_cli.cfg
    awx_nolog: yes
    awx_local_url: "http://localhost:{{ awx_container_port | default('80') }}"

  roles:

    - nephelaiio.plugins

  tasks:

    - name: include vars files
      include_vars:
        dir: "{{ item }}"
      loop: "{{ vars_dirs | list }}"
      ignore_errors: yes
      when: vars_dirs is defined

    - name: install tower cli
      pip:
        name: ansible-tower-cli
        state: present

    - name: create tower cli configuration file
      template:
        src: tower_cli.cfg.j2
        dest: "{{ awx_cli_conf }}"
        mode: 0600
      vars:
        host: "{{ awx_local_url }}"
        username: "{{ awx_admin_user | default('admin') }}"
        password: "{{ awx_admin_pass }}"
        verify_ssl: false
        verbose: false

    - block:

        - name: query credential types
          uri:
            url: "{{ awx_local_url }}/api/v2/credential_types/"
            method: GET
            body_format: json
            user: "{{ awx_admin_user | default('admin') }}"
            password: "{{ awx_admin_pass }}"
            force_basic_auth: yes
            status_code: 200
          register: credential_type_query
          tags:
            - always

        - name: set credential type dict
          set_fact:
            awx_credential_type_dict: "{{ credential_type_query.json.results | list | list_to_dict('kind') }}"
          tags:
            - always

        - name: manage awx settings
          tower_settings:
            name: "{{ item }}"
            value: "{{ awx_settings[item] | string }}"
          loop_control:
            label: "{{ item }}"
          loop: "{{ awx_settings.keys() | list | default([]) }}"
          ignore_errors: yes
          tags:
            - settings

        - name: destroy awx notifications
          include_tasks: config/notification_destroy.yml
          vars:
            organization: "{{ item.0 }}"
            notification: "{{ item.1 }}"
          loop_control:
            label: "{{ notification.name }}"
          loop: "{{ awx_organizations | subelements('notifications', skip_missing='yes') }}"
          when: organization.state | default('present') == 'absent' or notification.state | default('present') == 'absent'
          no_log: "{{ awx_nolog }}"

        - name: destroy awx job schedules
          include_tasks: config/schedule_destroy.yml
          vars:
            schedule: "{{ item }}"
          loop_control:
            label: "{{ schedule.name }}"
          loop: "{{ (awx_schedules | default([])) | list }}"
          when: schedule.state | default('present') == 'absent'
          no_log: "{{ awx_nolog }}"
          tags:
            - schedules

        - name: destroy awx workflows
          include_tasks:
            file: config/workflow_destroy.yml
            apply:
              tags:
                - workflows
          vars:
            organization: "{{ item.0 }}"
            workflow: "{{ item.1 }}"
          loop_control:
            label: "{{ workflow.name }}"
          loop: "{{ awx_organizations | subelements('workflows', skip_missing='yes') }}"
          no_log: "{{ awx_nolog }}"
          when: awx_workflow_manage | default('yes') | bool
          tags:
            - workflows

        - name: destroy absent awx job templates
          command: "awx-cli job_template delete -n {{ template.name | quote }}"
          vars:
            template: "{{ item }}"
          loop_control:
            label: "{{ template.name }}"
          loop: "{{ (awx_templates | default([])) | list }}"
          when: template.state | default('present') == 'absent'
          no_log: "{{ awx_nolog }}"
          tags:
            - templates

        - name: changes detection in jobs templates
          uri:
            url: "{{ awx_local_url }}/api/v2/job_templates/?page_size=1000"
            method: GET
            body_format: json
            user: "{{ awx_admin_user | default('admin') }}"
            password: "{{ awx_admin_pass }}"
            force_basic_auth: yes
            status_code: 200
          register: list_templates_query

        - name: set template list facts
          set_fact:
            list_templates: "{{ list_templates_query.json.results | list }}"

        - name: destroy modified awx job templates
          command: "awx-cli job_template delete -n {{ template.name | quote }}"
          vars:
            template: "{{ item }}"
          loop_control:
            label: "{{ item.name }}"
          loop: "{{ list_templates | default([]) }}"
          when: not (( item.created | iso8601_to_time | datetimeformat("%y-%b-%dT%H:%M") ) == ( item.modified | iso8601_to_time | datetimeformat("%y-%b-%dT%H:%M") ))

        - name: destroy awx inventories
          include_tasks:
            file: config/inventory_destroy.yml
            apply:
              tags:
                - inventories
          vars:
            organization: "{{ item.0 }}"
            inventory: "{{ item.1 }}"
          loop_control:
            label: "{{ inventory.name }}"
          loop: "{{ awx_organizations | subelements('inventories', skip_missing='yes') }}"
          when: organization.state | default('present') == 'absent' or inventory.state | default('present') == 'absent'
          tags:
            - inventories
          no_log: "{{ awx_nolog }}"

        - name: destroy awx projects
          tower_project:
            organization: "{{ organization.name }}"
            name: "{{ project.name }}"
            state: absent
          vars:
            organization: "{{ item.0 }}"
            project: "{{ item.1 }}"
          loop_control:
            label: "{{ project.name }}"
          loop: "{{ awx_organizations | subelements('projects', skip_missing='yes') }}"
          when: organization.state | default('present') == 'absent' or project.state | default('present') == 'absent'
          tags:
            - projects
          no_log: "{{ awx_nolog }}"

        - name: destroy awx credentials
          tower_credential:
            organization: "{{ organization.name }}"
            name: "{{ credential.name }}"
            kind: "{{ credential.kind }}"
            state: absent
          vars:
            organization: "{{ item.0 }}"
            credential: "{{ item.1 }}"
          loop_control:
            label: "{{ credential.name }}"
          loop: "{{ awx_organizations | subelements('credentials', skip_missing='yes') }}"
          when: organization.state | default('present') == 'absent' or credential.state | default('present') == 'absent'
          no_log: "{{ awx_nolog }}"
          tags:
            - credentials
          ignore_errors: yes

        - name: destroy awx organizations
          tower_organization:
            name: "{{ organization.name }}"
            state: absent
          vars:
            organization: "{{ item }}"
          loop_control:
            label: "{{ organization.name }}"
          loop: "{{ awx_organizations | list }}"
          when: organization.state | default('present') == 'absent'
          no_log: "{{ awx_nolog }}"

        - name: create awx organizations
          tower_organization:
            name: "{{ organization.name }}"
            state: present
          vars:
            organization: "{{ item }}"
          loop_control:
            label: "{{ organization.name }}"
          loop: "{{ awx_organizations | list }}"
          when: item.state | default('present') == 'present'
          no_log: "{{ awx_nolog }}"

        - name: manage awx teams
          tower_team:
            name: "{{ team.name }}"
            organization: "{{ team.organization }}"
            state: "{{ team.state | default('present') }}"
          loop_control:
            loop_var: team
            label: "{{ team.name }}"
          loop: "{{ awx_teams | default([]) }}"
          tags:
            - teams

        - name: create awx credentials
          tower_credential:
            organization: "{{ organization.name }}"
            name: "{{ credential.name }}"
            kind: "{{ credential.kind }}"
            state: present
            become_password: "{{ credential.become_password | default(omit) }}"
            become_username: "{{ credential.become_username | default(omit) }}"
            description: "{{ credential.description | default(omit) }}"
            password: "{{ credential.password | default(omit) }}"
            project: "{{ credential.project | default(omit) }}"
            ssh_key_data: "{{ credential.ssh_key_data | default(omit) }}"
            ssh_key_unlock: "{{ credential.ssh_key_unlock | default(omit) }}"
            team: "{{ credential.team | default(omit) }}"
            username: "{{ credential.username | default(omit) }}"
            vault_password: "{{ credential.vault_password | default(omit) }}"
          vars:
            organization: "{{ item.0 }}"
            credential: "{{ item.1 }}"
          loop_control:
            label: "{{ credential.name }}"
          loop: "{{ awx_organizations | subelements('credentials', skip_missing='yes') }}"
          when: organization.state | default('present') == 'present' and credential.state | default('present') == 'present'
          no_log: "{{ awx_nolog }}"
          tags:
            - credentials

        - name: query credentials
          uri:
            url: "{{ awx_local_url }}/api/v2/credentials/"
            method: GET
            body_format: json
            user: "{{ awx_admin_user | default('admin') }}"
            password: "{{ awx_admin_pass }}"
            force_basic_auth: yes
            status_code: 200
          register: credential_query
          tags:
            - always

        - name: set credential dict
          set_fact:
            awx_credential_dict: "{{ credential_query.json.results | list | list_to_dict('name') }}"
          tags:
            - always

        - name: associate credential vault ids
          command: >
            awx-cli credential modify
              -n {{ credential.name }}
              --credential-type {{ awx_credential_type_dict['vault'].id }}
              --inputs {{ inputs | to_json | quote }}
          changed_when: false
          vars:
            organization: "{{ item.0 }}"
            credential: "{{ item.1 }}"
            inputs:
              vault_password: "{{ credential.vault_password }}"
              vault_id: "{{ credential.vault_id }}"
          loop_control:
            label: "{{ credential.name }}"
          loop: "{{ awx_organizations | subelements('credentials', skip_missing='yes') }}"
          when:
            - organization.state | default('present') == 'present' and credential.state | default('present') == 'present'
            - credential.kind == 'vault'
            - "'vault_id' in credential"
          no_log: "{{ awx_nolog }}"
          tags:
            - credentials

        - name: create awx projects
          include_tasks:
            file: config/project_create.yml
            apply:
              tags:
                - projects
          vars:
            organization: "{{ item.0 }}"
            project: "{{ item.1 }}"
          loop_control:
            label: "{{ project.name }}"
          loop: "{{ awx_organizations | subelements('projects', skip_missing='yes') }}"
          when: organization.state | default('present') == 'present' and project.state | default('present') == 'present'
          tags:
            - projects
          no_log: "{{ awx_nolog }}"

        - name: create awx inventories
          include_tasks:
            file: config/inventory_create.yml
            apply:
              tags:
                - inventories
          vars:
            organization: "{{ item.0 }}"
            inventory: "{{ item.1 }}"
          loop_control:
            label: "{{ inventory.name }}"
          loop: "{{ awx_organizations | subelements('inventories', skip_missing='yes') }}"
          when: organization.state | default('present') == 'present' and inventory.state | default('present') == 'present'
          tags:
            - inventories
          no_log: "{{ awx_nolog }}"

        - name: create awx job templates
          include_tasks: config/template_create.yml
          vars:
            template: "{{ item }}"
          loop_control:
            label: "{{ template.name }}"
          loop: "{{ (awx_templates | default([])) | list }}"
          when: template.state | default('present') == 'present'
          no_log: "{{ awx_nolog }}"
          tags:
            - templates

        - name: create awx workflows
          include_tasks:
            file: config/workflow_create.yml
            apply:
              tags:
                - workflows
          vars:
            organization: "{{ item.0 }}"
            workflow: "{{ item.1 }}"
          loop_control:
            label: "{{ workflow.name }}"
          loop: "{{ awx_organizations | subelements('workflows', skip_missing='yes') }}"
          when:
            - organization.state | default('present') == 'present'
            - workflow.state | default('present') == 'present'
            - awx_workflow_manage | default('yes') | bool
          no_log: "{{ awx_nolog }}"
          tags:
            - workflows

        - name: create awx job schedules
          include_tasks: config/schedule_create.yml
          vars:
            schedule: "{{ item }}"
          loop_control:
            label: "{{ schedule.name }}"
          loop: "{{ (awx_schedules | default([])) | list }}"
          when: schedule.state | default('present') == 'present'
          no_log: "{{ awx_nolog }}"
          tags:
            - schedules

        - name: create awx notifications
          include_tasks: config/notification_create.yml
          vars:
            organization: "{{ item.0 }}"
            notification: "{{ item.1 }}"
          loop_control:
            label: "{{ notification.name }}"
          loop: "{{ awx_organizations | subelements('notifications', skip_missing='yes') }}"
          when: organization.state | default('present') == 'present' and notification.state | default('present') == 'present'
          no_log: "{{ awx_nolog }}"
          tags:
            - notifications

        - name: manage awx users
          tower_user:
            username: "{{ item.username }}"
            password: "{{ item.password }}"
            first_name: "{{ item.first_name | default(omit) }}"
            last_name: "{{ item.last_name | default(omit) }}"
            email: "{{ item.email | default(omit) }}"
            superuser: "{{ item.superuser | default(omit) }}"
            state: "{{ item.state | default('present') }}"
          loop_control:
            label: "{{ item.username }}"
          loop: "{{ awx_users | default([]) | list }}"
          no_log: "{{ awx_nolog }}"
          tags:
            - users

      run_once: yes
